// Builds src/lib/campaign-data.ts: 10 chapters × 10 levels from the frozen
// grid-v1 bank, which is already sorted by position-logic difficulty. Later
// levels add enemies, unit types, and pick more constrained enemy squares.
// Published level IDs must not be regenerated in place.
import { existsSync, writeFileSync } from 'node:fs';
import { GRIDS } from '../src/lib/source/grid-data.ts';
import { CAMPAIGN_CHAPTERS, chapterIndex } from '../src/lib/chapters.ts';
import { buildLevel, levelFile } from './level-builder.ts';

const destination = new URL('../src/lib/campaign-data.ts', import.meta.url);
if (existsSync(destination) && !process.argv.includes('--replace-unreleased'))
  throw new Error('campaign v1 already exists; use a new content version.');

const COUNT = 100;
const levels = Array.from({ length: COUNT }, (_, index) => {
  const c = chapterIndex(CAMPAIGN_CHAPTERS, index),
    t = index / (COUNT - 1);
  const { level, score } = buildLevel({
    id: `zhen-c1-${String(index + 1).padStart(3, '0')}`,
    source: GRIDS[index],
    units: CAMPAIGN_CHAPTERS[c].units,
    enemies: Math.round(8 + t * 12),
    seed: index * 104729 + 7,
    noise: 30 - t * 27,
    attempts: Math.round(40 + t * 760),
    // Later levels strongly prefer enemies only one or two cells can reach.
    cellWeight: Math.round(t * 24),
  });
  console.log(`${level.id} enemies=${level.enemies.length} reach=${score} quotas=${level.quotas.join(',')}`);
  return level;
});

writeFileSync(
  destination,
  levelFile(
    'CAMPAIGN_LEVELS',
    `// Generated by scripts/generate-campaign.ts from the frozen grid-v1 bank.\n` +
      `// Do not hand-edit or regenerate published IDs in place.`,
    levels,
  ),
);
