// Builds src/lib/level-data.ts: the 40 story (tutorial) levels from the frozen
// Bullpen double-grid bank. Published level IDs must not be regenerated in place.
import { writeFileSync } from 'node:fs';
import { HARD } from '../src/lib/source/hard-data.ts';
import { STORY_CHAPTERS, chapterIndex } from '../src/lib/chapters.ts';
import { buildLevel, levelFile } from './level-builder.ts';

const LEVEL_COUNT = 40;
const levels = Array.from({ length: LEVEL_COUNT }, (_, index) => {
  const chapter = STORY_CHAPTERS[chapterIndex(STORY_CHAPTERS, index)];
  const { level, score } = buildLevel({
    id: `zhen-v1-${String(index + 1).padStart(3, '0')}`,
    source: HARD[index],
    units: chapter.units,
    enemies: Math.round(6 + (index * 10) / (LEVEL_COUNT - 1)),
    seed: index * 7919 + 17,
    // Always feature the chapter's newest unit.
    feature: chapter.units.at(-1)!,
  });
  console.log(`${level.id} enemies=${level.enemies.length} reach=${score} quotas=${level.quotas.join(',')}`);
  return level;
});

writeFileSync(
  new URL('../src/lib/level-data.ts', import.meta.url),
  levelFile(
    'LEVELS',
    `// Generated by scripts/generate-levels.ts from the frozen double-grid v1 bank.\n` +
      `// Do not hand-edit or regenerate published IDs in place.`,
    levels,
  ),
);
