// Builds src/lib/level-data.ts from the frozen double-grid bank.
// Enemies only occupy non-solution cells, so every level keeps the bank's unique
// unit positions. Each level is built from a concrete answer, so full coverage
// is always achievable. Published level IDs must not be regenerated in place.
import { writeFileSync } from 'node:fs';
import { HARD } from '../src/lib/source/hard-data.ts';
import { CHAPTERS, chapterOf } from '../src/lib/chapters.ts';
import { solutionCells, solveAssignment } from '../src/lib/assign.ts';
import {
  DIRS,
  UNITS,
  coverage,
  encodePiece,
  type Dir,
  type UnitId,
} from '../src/lib/units.ts';
import type { Level } from '../src/lib/game.ts';

const LEVEL_COUNT = 40;
const ATTEMPTS = 600;

function rng(seed: number) {
  let state = ((seed + 1) * 2654435761) >>> 0 || 1;
  return () => {
    state ^= state << 13;
    state ^= state >>> 17;
    state ^= state << 5;
    return (state >>> 0) / 4294967296;
  };
}

function shuffle<T>(items: T[], random: () => number) {
  for (let i = items.length - 1; i > 0; i--) {
    const j = Math.floor(random() * (i + 1));
    [items[i], items[j]] = [items[j], items[i]];
  }
  return items;
}

function quotasFor(units: UnitId[], total: number, random: () => number) {
  const quotas = UNITS.map(() => 0),
    newest = units.at(-1)!,
    cap = (u: UnitId) => (u === 5 ? 3 : total);
  for (const u of units) quotas[u] = u === newest && units.length > 2 ? 3 : 1;
  while (quotas.reduce((a, b) => a + b, 0) < total) {
    const open = units.filter((u) => quotas[u] < cap(u));
    quotas[open[Math.floor(random() * open.length)]]++;
  }
  return quotas;
}

const levels: Level[] = [];
for (let index = 0; index < LEVEL_COUNT; index++) {
  const source = HARD[index],
    n = source.regions.length,
    cells = solutionCells(source),
    solutionSet = new Set(cells),
    chapter = CHAPTERS[chapterOf(index)],
    enemyTarget = Math.round(6 + (index * 10) / (LEVEL_COUNT - 1)),
    random = rng(index * 7919 + 17);
  // How many (cell, type, facing) choices could reach each square this chapter.
  const reachAll = Array<number>(n * n).fill(0);
  for (const cell of cells)
    for (const u of chapter.units)
      for (const d of DIRS)
        for (const x of coverage(cell, u, d, n)) reachAll[x]++;
  let best: { score: number; level: Level } | null = null;
  for (let attempt = 0; attempt < ATTEMPTS; attempt++) {
    const quotas = quotasFor(chapter.units, cells.length, random),
      types = shuffle(
        quotas.flatMap((q, u) => Array<UnitId>(q).fill(u as UnitId)),
        random,
      );
    const answer = cells.map((cell, k) => {
      const unit = types[k],
        useful = DIRS.filter((d) =>
          coverage(cell, unit, d, n).some((x) => !solutionSet.has(x)),
        ),
        dirs = useful.length ? useful : [...DIRS];
      return { unit, dir: dirs[Math.floor(random() * dirs.length)] as Dir };
    });
    const reach = new Map<number, number>();
    cells.forEach((cell, k) => {
      for (const x of coverage(cell, answer[k].unit, answer[k].dir, n))
        if (!solutionSet.has(x)) reach.set(x, reachAll[x]);
    });
    if (reach.size < enemyTarget) continue;
    // Always feature the chapter's newest unit with an enemy only it reaches in the answer.
    const newest = chapter.units.at(-1)!,
      featured = cells.flatMap((cell, k) =>
        answer[k].unit === newest
          ? coverage(cell, newest, answer[k].dir, n).filter((x) => reach.has(x))
          : [],
      );
    if (!featured.length) continue;
    const picked = new Set([featured[Math.floor(random() * featured.length)]]);
    const ranked = [...reach.keys()]
      .filter((x) => !picked.has(x))
      .map((x) => ({ x, key: reach.get(x)! + random() * 6 }))
      .sort((a, b) => a.key - b.key);
    for (const { x } of ranked) {
      if (picked.size >= enemyTarget) break;
      picked.add(x);
    }
    const enemies = [...picked].sort((a, b) => a - b),
      score = enemies.reduce((sum, x) => sum + reach.get(x)!, 0);
    if (best && score >= best.score) continue;
    best = {
      score,
      level: {
        id: `zhen-v1-${String(index + 1).padStart(3, '0')}`,
        source: source.id,
        regions: source.regions,
        solution: source.solution,
        cowsPerUnit: 2,
        enemies,
        quotas,
        answer: answer.map(encodePiece),
      },
    };
  }
  if (!best) throw new Error(`No candidate for level ${index + 1}`);
  if (!solveAssignment(best.level))
    throw new Error(`Level ${index + 1} has no full-coverage assignment`);
  levels.push(best.level);
  console.log(
    `${best.level.id} enemies=${best.level.enemies.length} reach=${best.score} quotas=${best.level.quotas.join(',')}`,
  );
}

writeFileSync(
  new URL('../src/lib/level-data.ts', import.meta.url),
  `// Generated by scripts/generate-levels.ts from the frozen double-grid v1 bank.\n` +
    `// Do not hand-edit or regenerate published IDs in place.\n` +
    `import type { Level } from './game.ts';\n\n` +
    `export const LEVELS: Level[] = [\n` +
    levels.map((l) => `  ${JSON.stringify(l)},`).join('\n') +
    `\n];\n`,
);
