// Builds src/lib/formation-data.ts: 100 enemy-free levels from the frozen
// grid-v2 bank, already sorted by position-logic difficulty. Only unit
// positions matter, so there are no quotas or answers beyond the solution.
// Published level IDs must not be regenerated in place.
import { existsSync, writeFileSync } from 'node:fs';
import { FORMATION_GRIDS } from '../src/lib/source/grid-v2-data.ts';
import { levelFile } from './level-builder.ts';
import type { Level } from '../src/lib/game.ts';

const destination = new URL('../src/lib/formation-data.ts', import.meta.url);
if (existsSync(destination) && !process.argv.includes('--replace-unreleased'))
  throw new Error('formation v1 already exists; use a new content version.');

const levels: Level[] = FORMATION_GRIDS.map((grid, index) => ({
  id: `zhen-f1-${String(index + 1).padStart(3, '0')}`,
  source: grid.id,
  regions: grid.regions,
  solution: grid.solution,
  cowsPerUnit: 2,
  enemies: [],
  quotas: [0, 0, 0, 0, 0, 0],
  answer: [],
  kind: 'formation',
}));

writeFileSync(
  destination,
  levelFile(
    'FORMATION_LEVELS',
    `// Generated by scripts/generate-formation.ts from the frozen grid-v2 bank.\n` +
      `// Do not hand-edit or regenerate published IDs in place.`,
    levels,
  ),
);
console.log(`saved ${levels.length} formation levels`);
